# -*- coding: utf-8 -*-
"""Assignment - Variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ht7wQrID3nfFcJQUNOcJqRr81wV8Srtl
"""

# Question 1 :  Write a Python program that asks the user to enter a
# temperature and specify whether it's in Celsius or Fahrenheit, converts the temperature to the opposite unit

temp=float(input('Enter the temperature '))
unit=input(' Enter the unit as c for Celsius and f for Fahrenheit ').upper()
if unit=='F':
    converted_temp=(temp-32)*5/9
    print(f"{temp:.2f}°F is {converted_temp:.2f}°C")
elif unit=='C':
    converted_temp =(temp*9/5)+32
    print(f"{temp:.2f}°C is {converted_temp:.2f}°F")
else:
    print('Invalid unit')

# Question 2 : Write a Python program to calculate the simple interest for a given principal amount,
# rate of interest, and time by prompting the user for inputs, and outputting both the simple interest and the total amount.


p_amount=float(input('Enter the principal amount '))
rate=float(input('Enter the rate of interest per annum '))
time=float(input('Enter the time '))
simple_interest=(p_amount*rate*time)/100
total_amount=p_amount+simple_interest

print(f"The simple interest is {simple_interest:.2f}")
print(f"The total amount is {total_amount:.2f}")

# Question 3 : Write a Python program that asks the user to enter an amount in their home currency (e.g., USD),
# asks for the target currency (e.g., EUR), uses predefined conversion rates to calculate the equivalent amount,
# and outputs the converted amount in the target currency.

currency_INR=float(input('Enter the amount in home currency '))
currency_target=input('Enter the target currency ').upper()

#taking some predefined rates not dynamic as the rates changes daily

rates_from_inr = {
    "USD": 0.0120,   # US Dollar
    "EUR": 0.0110,   # Euro
    "GBP": 0.0096,   # British Pound
    "JPY": 1.80,     # Japanese Yen
    "AUD": 0.0180,   # Australian Dollar
    "CAD": 0.0160,   # Canadian Dollar
    "SGD": 0.0162,   # Singapore Dollar
    "CHF": 0.0104,   # Swiss Franc
    "CNY": 0.0870,   # Chinese Yuan
}

if currency_target in rates_from_inr:
    conversion_rate = rates_from_inr[currency_target]
    converted_amount = currency_INR * conversion_rate
    print(f"{currency_INR:.2f} INR is {converted_amount:.2f} {currency_target}")
else:
    print("Invalid target currency")

# Question 4 : Write a Python program that asks for the user's weight (kg) and height (m),
# calculates the BMI , and outputs the BMI with a category (underweight, normal weight, overweight, or obese)
#  based on standard thresholds.

weight=float(input('Enter the weight in kg '))
height=float(input('Enter the height in m '))

bmi=weight/(height**2)

if bmi < 18.5:
        category = "Underweight"
elif bmi < 25:
        category = "Normal weight"
elif bmi < 30:
        category = "Overweight"
else:
        category = "Obese"

print(f"The BMI of the user is {bmi:.2f} and it comes under {category} category")

# Question 5 : Write a Python program to convert a user-input distance between miles and kilometers
# and output the converted distance using the conversion factors 1 mile = 1.60934 kilometers and 1 kilometer = 0.621371 miles.


dist=float(input('Enter the distance '))
unit=input('Enter the unit as m for miles and k for kilometers ').lower()

if unit=='m':
  converted_dist=dist*1.60934
  print(f"{dist:.2f} miles is {converted_dist:.4f} kilometers")

elif unit=='k':
  converted_dist=dist*0.621371
  print(f"{dist:.2f} kilometers is {converted_dist:.4f} miles")

else:
  print('Invalid unit')